### ISSUE TITLE
The  relationship between *.fasta *.sti *.tri ?

### ISSUE THREAD

**Issue by wangzhenkeep** [Yandell-Lab/taxonomer_0.5#1]
I am try to run the taxonomer on my machine.But I do not know what the *.tri file is.Can you give me an example file  based on real data  about the *.fasta *.sti *.tri. My emali wangzhen@celloud.cn.   Thanks!!!

**Comment by 4ureliek** [comment]
Hi,
One way to think about the .tri file is to consider it as being the "taxonomy map" (relationships between nodes = parents and children) and the .sti file as the way to fill that taxonomy with sequences (the nodes each sequence should go to).
For example, let's say that your database is made of two sequences that are both from E.coli, with a taxonomic lineage (simplified with 4 nodes) as follow:
Prokaryotes;Bacteria;Proteobacteria;Ecoli

All the nodes will be converted to numbers: 1;2;3;4 
the .tri is the taxonomy map of these nodes and will look like this:

```
>1
0
>2
1
>3
2
>4
3
```

This means that the node 3 is the parent of the node 4.
The only restrictions imposed by taxonomer when defining a taxonomy is that every child has exactly 1 parent (but a parent can have many children) and the tree be rooted at taxid '1' with 0 as its parent (which explains the first 2 lines).

Then, the sti file will contain the information of where the 2 sequences in the database should go, here the node 4. However, Taxonomer requires that the sequences be renamed as integers (the ones in the tri excluded, but they don't need to be sorted). For this example we could have 5 and 6 as sequence names, and the .sti will be:

```
>5
4
>6
4
```

This means that the fasta file also needs to look like this:

```
>5    old_header
AATTGGCCAAAATTGGCCAAAATTGGCCAAAATTGGCCAAAATTGGCCAA
>6    old_header
TTAAGGCCTTTTAAGGCCTTTTAAGGCCTTTTAAGGCCTTTTAAGGCCTT
```

So to build these, the information required is to know which node the sequences are assigned to (e.g. species names) as well as the complete taxonomy of the nodes (phylum, class, order, family, etc).

**Comment by wangzhenkeep** [comment]
Thank you! Got it!

**Comment by wangzhenkeep** [comment]
my commands as follows:
1. java -jar kanalyze.jar count -k 31 -d 30 -l 30 -o test -m hex -rcanonical -f fasta db.fasta
2. python build_db.py  test_binner  test  db.sti db.fasta
3. python classify_reads.py  test_binner  db.tri db.sti 1.fasta result

The result:  
U       1
U       2

 U represents the Unkonw ? the file 1.fasta and db.fasta are same.  I created File db.sti and db.tri by manually.   What`s wrong with it ?

**Comment by wangzhenkeep** [comment]
Only the Numbers in .tri  .sti, how do you know what is the classification of the Numbers represent ?  Converts Numbers into the classification by myself?
Do you have the script to generate .tri and .sti ?  
Thanks!!!

**Comment by 4ureliek** [comment]
Could you share your .sti, .tri and .fa files so I could check why it is not working in your hands?
Thanks!

**Comment by wangzhenkeep** [comment]
# .fasta:

>1   CICDC94777     1434    S004089613  Lineage=Root;rootrank;Bacteria;domain;"Actinobacteria";phylum;Actinobacteria;class;Actinobacteridae;subclass;Actinomycetales;order;Streptomycineae;suborder;Streptomycetaceae;family;Streptomyces;genus
tggctggtgcgtagacgagagagtgtcgaacgatgaaccgctttcgggcggggattagtggcgaacgggtgagtaacacg
tgggcaatctgccctgcactctgggacaagccctggaaacggggtctaataccggatatgactgtccatcgcatggtgga
tggtgtaaagctccggcggtgcaggatgagcccgcggcctatcagcttgttggtgaggtagtggctcaccaaggcgacga
cgggtagccggcctgagagggcgaccggccacactgggactgagacacggcccagactcctacgggaggcagcagtgggg
aatattgcacaatgggcgaaagcctgatgcagcgacgccgcgtgagggatgacggccttcgggttgtaaacctctttcag
cagggaagaagcgaaagtgacggtacctgcagaagaagcgccggctaactacgtgccagcagccgcggtaatacgtaggg
cgcaagcgttgtccggaattattgggcgtaaagagctcgtaggcggcttgtcacgtcggttgtgaaagcccggggcttaa
ccccgggtctgcagtcgatacgggcaggctagagttcggtaggggagatcggaattcctggtgtagcggtgaaatgcgca
gatatcaggaggaacaccggtggcgaaggcggatctctgggccgatactgacgctgaggagcgaaagcgtggggagcgaa
caggattagataccctggtagtccacgccgtaaacggtgggcactaggtgtgggcaacattccacgttgtccgtgccgca
gctaacgcattaagtgccccgcctggggagtacggccgcaaggctaaaactcaaaggaattgacgggggcccgcacaagc
ggcggagcatgtggcttaattcgacgcaacgcgaagaaccttaccaaggcttgacatacaccggaaacgtctggagacag
gcgcccccttgtggtcggtgtacaggtggtgcatggctgtcgtcagctcgtgtcgtgagatgttgggttaagtcccgcaa
cgagcgcaacccttgtcccgtgttgccagcaggcccttgtggtgctggggactcacgggagaccgccggggtcaactcgg
aggaaggtggggacgacgtcaagtcatcatgccccttatgtcttgggctgcacacgtgctacaatggccggtacaatgag
ctgcgataccgcgaggtggagcgaatctcaaaaagccggtctcagttcggattggggtctgcaactcgaccccatgaagt
cggagtcgctagtaatcgcagatcagcattgctgcggtgaatacgttcccgggccttgtacacaccgcccgtcacgtcac
gaaagtcggtaacacccgaagccggtggcctcaacctcgttgtcaagggagctgtagacggagagcgacctcgc
>2  CICDC116532    1480    S001292447      Azospirillum sp. NS01; NS01; NEU1208   Lineage=Root;rootrank;Bacteria;domain;"Proteobacteria";phylum;Alphaproteobacteria;class;Rhodospirillales;order;Rhodospirillaceae;family;Azospirillum;genus
aacgaacgctggcggcatgcctaacacatgcaagtcgaacgarggcttcggccytagtggcgcacgggtgagtaacacgt
gggaacctgccttatggttcgggataacgtctggaaacggacgctaacaccggatgtgcccttcgggggaaagtttacgc
catgagaggggcccgcgtccgattaggtagttggtggggtaatggcccaccaagccgacgatcggtagctggtctgagag
gatgatcagccacactgggactgagacacggcccagactcctacgggaggcagcagtggggaatattggacaatgggggc
aaccctgatccagcaatgccgcgtgagtgatgaaggccttagggttgtaaagctctttcgcacgcgacgatgatgacggt
agcgtgagaagaagccccggctaacttcgtgccagcagccgcggtaatacgaagggggcgagcgttgttcggaattactg
ggcgtaaagggcgcgtaggcggcccgatcagtcagatgtgaaagccccgggctcaacctgggaactgcatttgatactgt
cgggcttgagttccggagaggatggtggaattcccagtgtagaggtgaaattcgtagatattgggaagaacaccggtggc
gaaggcggccatctggacggacactgacgctgaggcgcgaaagcgtggggagcaaacaggattagataccctggtagtcc
acgccgtaaacgatgaatgctagacgctggggtgcatgcacttcggtgtcgccgctaacgcattaagcattccgcctggg
gagtacggccgcaaggttaaaactcaaaggaattgacgggggcccgcacaagcggtggagcatgtggtttaattcgaagc
aacgcgcagaaccttaccaacccttgacatgtccattgccggtccgagagattggaccttcagttcggctggatggaaca
caggtgctgcatggctgtcgtcagctcgtgtcgtgagatgttgggttaagtcccgcaacgagcgcaacccctaccgccag
ttgccatcattcagttgggcactctggtggaactgccggtgacaagccggaggaaggcggggatgacgtcaagtcctcat
ggcccttatgggttgggctacacacgtgctacaatggcggtgacagtgggacgcgaagtcgcaagatggagcaaatcccc
aaaagccgtctcagttcggattgcactctgcaactcgggtgcatgaagttggaatcgctagtaatcgcggatcagcacgc
cgcggtgaatacgttcccgggccttgtacacaccgcccgtcacaccatgggagttggctttacccgaaggtggtgcgcta
accggcaacggaggcagccaaccacggtcaggtcagcgactggggtgaagtcgtaacaaggtagccgtaggggaacc

# .sti:

>1
106
>2
111

# .tri:

>101
102
>102
103
>103
104
>104
105
>105
106
>101
107
>107
108
>108
109
>109
110
>110
111

**Comment by 4ureliek** [comment]
Hi,
See the README, I quote:

> The only retrictions imposed by taxonomer when defining a taxonomy is that every child has exactly 1 parent and the tree be rooted at taxid '1' with 0 as its parent.

It is not working because 1) you forgot to put the 

```
>1
0
```

At the beginning of the .tri

2) you have one taxID with 2 parents:

```
>101
107
>101
102
```

**Comment by 4ureliek** [comment]
I added scripts to help out. Note that your fasta headers won't work - they have spaces that you should replace, for example by "_", with a command line such as:

`sed 's/ /_/g' fastafile.fa > fastafile.nospaces.fa`

**Comment by wangzhenkeep** [comment]
oooooo,sorry about I didn't put enough attention on reading README. And I change it,but still have something wrong.The sequences  in  the input file is same with the fasta file.The result is still like this:
U       A
U       B
my files are as below:

# fasta:

>1001   Lineage=Root;rootrank;Bacteria;domain;"Actinobacteria";phylum;Actinobacteria;class;Actinobacteridae;subclass;Actinomycetales;order;Streptomycineae;suborder;Streptomycetaceae;family;Streptomyces;genus
tggctggtgcgtagacgagagagtgtcgaacgatgaaccgctttcgggcggggattagtggcgaacgggtgagtaacacg
tgggcaatctgccctgcactctgggacaagccctggaaacggggtctaataccggatatgactgtccatcgcatggtgga
tggtgtaaagctccggcggtgcaggatgagcccgcggcctatcagcttgttggtgaggtagtggctcaccaaggcgacga
cgggtagccggcctgagagggcgaccggccacactgggactgagacacggcccagactcctacgggaggcagcagtgggg
aatattgcacaatgggcgaaagcctgatgcagcgacgccgcgtgagggatgacggccttcgggttgtaaacctctttcag
cagggaagaagcgaaagtgacggtacctgcagaagaagcgccggctaactacgtgccagcagccgcggtaatacgtaggg
cgcaagcgttgtccggaattattgggcgtaaagagctcgtaggcggcttgtcacgtcggttgtgaaagcccggggcttaa
ccccgggtctgcagtcgatacgggcaggctagagttcggtaggggagatcggaattcctggtgtagcggtgaaatgcgca
gatatcaggaggaacaccggtggcgaaggcggatctctgggccgatactgacgctgaggagcgaaagcgtggggagcgaa
caggattagataccctggtagtccacgccgtaaacggtgggcactaggtgtgggcaacattccacgttgtccgtgccgca
gctaacgcattaagtgccccgcctggggagtacggccgcaaggctaaaactcaaaggaattgacgggggcccgcacaagc
ggcggagcatgtggcttaattcgacgcaacgcgaagaaccttaccaaggcttgacatacaccggaaacgtctggagacag
gcgcccccttgtggtcggtgtacaggtggtgcatggctgtcgtcagctcgtgtcgtgagatgttgggttaagtcccgcaa
cgagcgcaacccttgtcccgtgttgccagcaggcccttgtggtgctggggactcacgggagaccgccggggtcaactcgg
aggaaggtggggacgacgtcaagtcatcatgccccttatgtcttgggctgcacacgtgctacaatggccggtacaatgag
ctgcgataccgcgaggtggagcgaatctcaaaaagccggtctcagttcggattggggtctgcaactcgaccccatgaagt
cggagtcgctagtaatcgcagatcagcattgctgcggtgaatacgttcccgggccttgtacacaccgcccgtcacgtcac
gaaagtcggtaacacccgaagccggtggcctcaacctcgttgtcaagggagctgtagacggagagcgacctcgc
>1002   Lineage=Root;rootrank;Bacteria;domain;"Proteobacteria";phylum;Alphaproteobacteria;class;Rhodospirillales;order;Rhodospirillaceae;family;Azospirillum;genus
aacgaacgctggcggcatgcctaacacatgcaagtcgaacgarggcttcggccytagtggcgcacgggtgagtaacacgt
gggaacctgccttatggttcgggataacgtctggaaacggacgctaacaccggatgtgcccttcgggggaaagtttacgc
catgagaggggcccgcgtccgattaggtagttggtggggtaatggcccaccaagccgacgatcggtagctggtctgagag
gatgatcagccacactgggactgagacacggcccagactcctacgggaggcagcagtggggaatattggacaatgggggc
aaccctgatccagcaatgccgcgtgagtgatgaaggccttagggttgtaaagctctttcgcacgcgacgatgatgacggt
agcgtgagaagaagccccggctaacttcgtgccagcagccgcggtaatacgaagggggcgagcgttgttcggaattactg
ggcgtaaagggcgcgtaggcggcccgatcagtcagatgtgaaagccccgggctcaacctgggaactgcatttgatactgt
cgggcttgagttccggagaggatggtggaattcccagtgtagaggtgaaattcgtagatattgggaagaacaccggtggc
gaaggcggccatctggacggacactgacgctgaggcgcgaaagcgtggggagcaaacaggattagataccctggtagtcc
acgccgtaaacgatgaatgctagacgctggggtgcatgcacttcggtgtcgccgctaacgcattaagcattccgcctggg
gagtacggccgcaaggttaaaactcaaaggaattgacgggggcccgcacaagcggtggagcatgtggtttaattcgaagc
aacgcgcagaaccttaccaacccttgacatgtccattgccggtccgagagattggaccttcagttcggctggatggaaca
caggtgctgcatggctgtcgtcagctcgtgtcgtgagatgttgggttaagtcccgcaacgagcgcaacccctaccgccag
ttgccatcattcagttgggcactctggtggaactgccggtgacaagccggaggaaggcggggatgacgtcaagtcctcat
ggcccttatgggttgggctacacacgtgctacaatggcggtgacagtgggacgcgaagtcgcaagatggagcaaatcccc
aaaagccgtctcagttcggattgcactctgcaactcgggtgcatgaagttggaatcgctagtaatcgcggatcagcacgc
cgcggtgaatacgttcccgggccttgtacacaccgcccgtcacaccatgggagttggctttacccgaaggtggtgcgcta
accggcaacggaggcagccaaccacggtcaggtcagcgactggggtgaagtcgtaacaaggtagccgtaggggaacc

# .sti:

>1001
5
>1002
10

# .tri:

>1
0
>2
1
>3
2
>4
3
>5
4
>6
0
>7
6
>8
7
>9
8
>10
9

# input file:

>A
tggctggtgcgtagacgagagagtgtcgaacgatgaaccgctttcgggcggggattagtggcgaacgggtgagtaacacg
tgggcaatctgccctgcactctgggacaagccctggaaacggggtctaataccggatatgactgtccatcgcatggtgga
tggtgtaaagctccggcggtgcaggatgagcccgcggcctatcagcttgttggtgaggtagtggctcaccaaggcgacga
cgggtagccggcctgagagggcgaccggccacactgggactgagacacggcccagactcctacgggaggcagcagtgggg
aatattgcacaatgggcgaaagcctgatgcagcgacgccgcgtgagggatgacggccttcgggttgtaaacctctttcag
cagggaagaagcgaaagtgacggtacctgcagaagaagcgccggctaactacgtgccagcagccgcggtaatacgtaggg
cgcaagcgttgtccggaattattgggcgtaaagagctcgtaggcggcttgtcacgtcggttgtgaaagcccggggcttaa
ccccgggtctgcagtcgatacgggcaggctagagttcggtaggggagatcggaattcctggtgtagcggtgaaatgcgca
gatatcaggaggaacaccggtggcgaaggcggatctctgggccgatactgacgctgaggagcgaaagcgtggggagcgaa
caggattagataccctggtagtccacgccgtaaacggtgggcactaggtgtgggcaacattccacgttgtccgtgccgca
gctaacgcattaagtgccccgcctggggagtacggccgcaaggctaaaactcaaaggaattgacgggggcccgcacaagc
ggcggagcatgtggcttaattcgacgcaacgcgaagaaccttaccaaggcttgacatacaccggaaacgtctggagacag
gcgcccccttgtggtcggtgtacaggtggtgcatggctgtcgtcagctcgtgtcgtgagatgttgggttaagtcccgcaa
cgagcgcaacccttgtcccgtgttgccagcaggcccttgtggtgctggggactcacgggagaccgccggggtcaactcgg
aggaaggtggggacgacgtcaagtcatcatgccccttatgtcttgggctgcacacgtgctacaatggccggtacaatgag
ctgcgataccgcgaggtggagcgaatctcaaaaagccggtctcagttcggattggggtctgcaactcgaccccatgaagt
cggagtcgctagtaatcgcagatcagcattgctgcggtgaatacgttcccgggccttgtacacaccgcccgtcacgtcac
gaaagtcggtaacacccgaagccggtggcctcaacctcgttgtcaagggagctgtagacggagagcgacctcgc
>B
aacgaacgctggcggcatgcctaacacatgcaagtcgaacgarggcttcggccytagtggcgcacgggtgagtaacacgt
gggaacctgccttatggttcgggataacgtctggaaacggacgctaacaccggatgtgcccttcgggggaaagtttacgc
catgagaggggcccgcgtccgattaggtagttggtggggtaatggcccaccaagccgacgatcggtagctggtctgagag
gatgatcagccacactgggactgagacacggcccagactcctacgggaggcagcagtggggaatattggacaatgggggc
aaccctgatccagcaatgccgcgtgagtgatgaaggccttagggttgtaaagctctttcgcacgcgacgatgatgacggt
agcgtgagaagaagccccggctaacttcgtgccagcagccgcggtaatacgaagggggcgagcgttgttcggaattactg
ggcgtaaagggcgcgtaggcggcccgatcagtcagatgtgaaagccccgggctcaacctgggaactgcatttgatactgt
cgggcttgagttccggagaggatggtggaattcccagtgtagaggtgaaattcgtagatattgggaagaacaccggtggc
gaaggcggccatctggacggacactgacgctgaggcgcgaaagcgtggggagcaaacaggattagataccctggtagtcc
acgccgtaaacgatgaatgctagacgctggggtgcatgcacttcggtgtcgccgctaacgcattaagcattccgcctggg
gagtacggccgcaaggttaaaactcaaaggaattgacgggggcccgcacaagcggtggagcatgtggtttaattcgaagc
aacgcgcagaaccttaccaacccttgacatgtccattgccggtccgagagattggaccttcagttcggctggatggaaca
caggtgctgcatggctgtcgtcagctcgtgtcgtgagatgttgggttaagtcccgcaacgagcgcaacccctaccgccag
ttgccatcattcagttgggcactctggtggaactgccggtgacaagccggaggaaggcggggatgacgtcaagtcctcat
ggcccttatgggttgggctacacacgtgctacaatggcggtgacagtgggacgcgaagtcgcaagatggagcaaatcccc
aaaagccgtctcagttcggattgcactctgcaactcgggtgcatgaagttggaatcgctagtaatcgcggatcagcacgc
cgcggtgaatacgttcccgggccttgtacacaccgcccgtcacaccatgggagttggctttacccgaaggtggtgcgcta
accggcaacggaggcagccaaccacggtcaggtcagcgactggggtgaagtcgtaacaaggtagccgtaggggaacc

**Comment by 4ureliek** [comment]
Your sequences are in lower cases, and Taxonomer ignore any kmers with lower sequences. It works in my hands once I rewrite the sequences in uppercase (and indeed this is not in the Readme, I will add it)
You can now use the script in Utils to build the sti, tri and fasta files, and to rewrite in uppercase just use the option -u

Side note, you have "test_binner" in the command lines you shared; binning and classifying are two different things and here you are building a classification database, not a binner.

**Comment by wangzhenkeep** [comment]
Yes, I have "test_binner"in the command ,but without arguments "-binner". Is it rigth?  Or how could I build a db for classification ?  My pouprse to use your pipline is to known the  microbial community profiles of my data. Can you tell me the  correct  commands?

my commands as follows，is it right ?
1. java -jar kanalyze.jar count -k 31 -d 30 -l 30 -o test -m hex -rcanonical -f fasta db.fasta
2. python build_db.py test_binner test db.sti db.fasta
3. python classify_reads.py test_binner db.tri db.sti 1.fasta result

**Comment by 4ureliek** [comment]
Hi, 
yes it is right, I just figured I should mention this. 
Like I said, your command lines work for me as long as the sequences are in uppercase.
Remember you can also use taxonomer.com or taxonomer.iobio.io

**Comment by wangzhenkeep** [comment]
I have corrected what you said.But  the result is also like this(database alignment to himself):
U       Seq_ID1
U       Seq_ID2
There is no error in the process of the program is running.I know the websites  taxonomer.com and taxonomer.iobio.io. And  I want use my own database. if  it is convenient ,could you give me the example file to build database、classifying? my email:  wangzhen@celloud.cn,Thanks!!!

**Comment by 4ureliek** [comment]
Hi,
Here are the files I used. As for the command lines they were the same as yours (see below), except that I ran the script that is in the Utils to prep the files (the one I uploaded recently). Note that you need to have uppercases for the fasta file you use to build the database as well, not just the sequences you classify.

java -jar kanalyze-0.9.7/kanalyze.jar count -k 31 -d 3 -l 3 -o test.uc -m hex -rcanonical -f fasta test.uc.fa
python build_db.py test.uc.db test test.sti test.uc.fa
python classify_reads.py test.uc.db test.tri test.sti test.uc.fa test.uc.taxo

Files:
[tests.zip](https://github.com/Yandell-Lab/taxonomer_0.5/files/385390/tests.zip)

Hopefully that helps.

**Comment by wangzhenkeep** [comment]
Thank you!  I know the reason. It  was coused by different versions of kanalyze.jar. 

## The result for kanalyze-2.0.0 is:

0x00096B7BDA3EAB^@^@1
0x001D028E1AA959^@^@2
0x0025ADDF68FAAD^@^@1
0x0025B74DA3E477^@^@1
0x004A3C857ACB51^@^@1
0x005139D59FB9A9^@^@1
0x005DFD2A820980^@^@1
0x0063839867AAE4^@^@1
0x00686705A3B95F^@^@1
0x006AB705A3387B^@^@1
0x006BA91AEEA413^@^@1
0x006DE88A6557EE^@^@1

## The result for kanalyze-0.9.7 is:

0x00096B74BDA3EAB7      1
0x001D0283E1AA9591      1
0x0025ADD2F68FAADE      1
0x005DFD24A820980B      1
0x006867045A3B95F6      1
0x006AB70C5A3387B5      1
0x006BA91CAEEA413D      1
0x006DE884A6557EEB      1
0x00740A0F86AA5644      1
0x007F5560A9135AEF      1
0x0089DB29A7ED1B6B      1
0x0089FC415C297D34      1
0x008AFC4158296D35      1
0x0095AA7C156ADE4B      1
0x0096B74BDA3EAB79      1
