### ISSUE TITLE
What`s the meaning of each tabs?

### ISSUE THREAD

**Issue by yeli7068** [Yandell-Lab/taxonomer_0.5#2]
Hi,

Thanks for your works. I tried taxonomer locally and I found the results from classify_reads.py were hard to understand. 

Here is one of the results:

C   KFALO:00070:01728   32  33  32  1   5535.943359 2928.200439 1434

Could you please tell me how to understand the results?

**Comment by 4ureliek** [comment]
Hi,
The tabs are as follow:
`<classified/unclassified> <read_ID> <tax_ID> <seq_ID> <depth> <number_of_hits_with_equal_score> <max_score> <average_score> <read_length>`

`seq_ID` is not reliable if the column "number_of_hits_with_equal_score" is more than 1.

The tax_ID and seq_ID are the ones from the .tri and .sti file

Cheers
