### ISSUE TITLE
if a  read is the same with  4 sequences in db, what is the result?

### ISSUE THREAD

**Issue by wangzhenkeep** [Yandell-Lab/taxonomer_0.5#3]
For example:
**db**
>1
xxxxxGCTCAGGACGAACGCTGGCGGCGTGCCTAATAxxxxx
>2
xxxxxxxxGCTCAGGACGAACGCTGGCGGCGTGCCTAATAxxxxxxx
>3
xxGCTCAGGACGAACGCTGGCGGCGTGCCTAATAxx
>4
xxxxxxxxxxxGCTCAGGACGAACGCTGGCGGCGTGCCTAATAxx
**read**
@M04030:16:000000000-AU89C:1:1114:26344:9601_1
GCTCAGGACGAACGCTGGCGGCGTGCCTAATA
+
GGGHHGGHGHHHHHHHHHHHHHHHHHGGG

How about the result? It will report all or only one?if just one of them,which one  will be report?

**Comment by 4ureliek** [comment]
Hi,

If the xxx sequences in the db do not carry any kmer in common with your read, then this read will have the same score to these 4 sequences in the database (such cases are called ties). 
If you ask the classifier to output the ties, you will see the 4 results in the output. If you don't, the result will depend on how these sequences are related in your taxonomy: the taxID in the output will be the one of the closest common parental node. For example, if these 4 sequences are of the same species, and are all in the same terminal node, the taxID of this node will be in the output (and the refID in the output will be one of these 4). 

However, note that if one of these 4 sequences in the db contain additional kmers from the read, it will get the highest score and the read will classify there.

Also, don't forget that the .tri needs to start with
>1
0
So you should not have any sequence with the number 1 as its header

Hope that helps,
Cheers,
Aurelie

PS: the best is always to test the behavior yourself with sample files - to confirm my answer, that is what I did (with 21 mers), by replacing the XXX by random ATGC; I tested with your 4 sequences only, and then a sequence that was the same as your first sequence + a 21 mer from the read again - in the latter case, the read classified to that sequence.
