### ISSUE TITLE
How the scores are calculated 

### ISSUE THREAD

**Issue by yeli7068** [Yandell-Lab/taxonomer_0.5#5]
Hi,

Congratulations on your works. I followed the instructions and build the database with kmer 21. Part of results are as followings:

C KFALO:02656:00841 11084 9972404 1 2 16.593258 16.106699 218
C KFALO:01142:02386 11053 926463738 1 1 67439.84375 8847.392578 170

For the first one, it turned out the result is against with online NCBI blast. For the second one, it is accordant with NCBI blast.

I am wondering how the scores are calculated and how to set a threshold.

Cheers

**Comment by 4ureliek** [comment]
Hi,

Your first classification result has a score of only 16, this is indeed low. From my experience, you may want to filter out things with a score < 40, or at least < 30 if you don't want to be too stringent. However, the score will depend on the database, so it is hard to give a definite answer. You could plot the density of scores and see how it looks like, for example, that might help set a threshold?

Also, maybe his reference sequence has some low complexity sequences in it. If yes, you may want to mask the sequences in the database for simple repeats or low complexity (seg for proteins, Repeat Masker with the appropriate options for DNA).

Cheers,
Aurelie

**Comment by yeli7068** [comment]
Hi,

Thanks for your quick response. It seemed the scores in Taxonomer were similar with combination of bit-score and e-value used in BLAST. 

In addition, binner database construction were introduced. I supposed that the way to build the binner database will lead the database with different or same kmers. But the scripts classify_reads.py has a parameters to set the kmer and kmer_cutoffs. I am kind of confused. I noticed that the optimal k-mer cutoffs for bin assignments were different for different organism. How to make sure that the kmer_cutoffs suitable for different organism? 

If I had three fasta files for human, viruseses and rRNA collections. The first question is shall I build different kmer_counts for each orgamism or I build one kmer_counts with a concentrate file from these above three files?  

Any helps from you will be highly appreciated.

**Comment by 4ureliek** [comment]
Hi,

I am not sure I follow exactly what you are asking; please let me know if I am wrong:
- you have a binner database
- you first bin your sequences to determine the organism
- and then you classify against a classification database
?

The kmer_cutoff in build_db.py is set to 10,000 which means that kmers that are found more than 10,000 times in the database will be kicked out. Unless you have a specific reason to lower this, I would just keep that. Highly frequent kmers in the database will have lower scores, so they won't affect the read/sequence classification too much. 

Then there is the kmer_cutoff in classify_reads.py, which is only if you wish to use a different cutoff than the database.

The kmer size is quite critical, and is discussed in the paper. However, 21nt seems like a good size overall. 

I am not sure what you mean by building kmer_counts?
