### ISSUE TITLE
pipeline analysis on local server

### ISSUE THREAD

**Issue by jingzhejiang** [Yandell-Lab/taxonomer_0.5#6]
Thank you for developing such a great tool! We have a lot of libraries, due to the limitations of network upload speed, making us very difficult to fully use the taxonomer website. I know there is a full repository, but it looks a little complicated for us. I wonder that if you have an integrated package, which I can installed on my local server? Through the implementation of a simple pipeline command, then I can get the same results as on your site. Thank you!

**Comment by 4ureliek** [comment]
We do not have such package. Also, I should mention that the Taxonomer.com outputs are a specific integrated pipeline. Using this repository and command lines, you would also have to parse the outputs of the binner and then of the classifier. Thus, even with a large amount of libraries, I would encourage you to use Taxonomer.com; but if you end up using the code from this repository, let us know if you do not manage to go through the instructions.

**Comment by jingzhejiang** [comment]
Hi! I was having trouble using the taxonomer.com. I have uploaded all the data to the site, but when I try to run a full analysis, it always displayed: 1st in queue. But there is no task in processing in front of the task. This situation has been going on for a few weeks, what's the problem?

**Comment by 4ureliek** [comment]
Hi,
Have you tried to cancel and restart? I have ran full analyses in the last few days and it's been working. You should contact the team in charge of Taxonomer.com directly - see https://www.taxonomer.com/feedback or http://idbydna.com/
Cheers
