### ISSUE TITLE
Official databases and taxonomy

### ISSUE THREAD

**Issue by tantrev** [Yandell-Lab/taxonomer_0.5#7]
Hello!  First off, thank you for this phenomenal software.

I am just wondering if might be possible to get a copy of the databases and taxonomy files used on the taxonomer.com site?  The official databases work great for my needs, I just have thousands of files that I would like to run against them (a few more than the 3 limited by the site :P).

**Comment by 4ureliek** [comment]
Hi,
You can build your own databases with the code in GitHub and from the required fasta files. The different databases are listed in taxonomer.com FAQ (see below, cc from https://www.taxonomer.com/faq). Note that to mimic the website results, separated classification databases will be needed to classify reads based on where they were binned (see the FAQ).
Databases:
    HumanGRCh37 reference genome and annotated transcripts
    BacteriaGreengenes and UniRef50
    ViralUniref 90
    FungalUNITE
    PhageUniref 90

The databases that we have built for Taxonomer.com have become very large (lots of memory is required to use them), and we are still developing them, involving large research efforts on our end that are still unpublished. Perhaps we could just collaborate in some way and run your samples locally, so you could get outputs comparable to taxonomer.com?
You can email me at 4urelie.k (at) gmail (dot) com

**Comment by tantrev** [comment]
Thank you!  I really appreciate all the information.  I saw the databases listed in the supplemental, I just got a little tripped-up when it came to the taxonomy side of things.  And that is an incredibly generous offer, thank you!  The data's mostly from single-cell RNA-sequencing, so I should probably play around with some bulk files first (to justify further exploration) before potentially wasting your time. If I find anything interesting, we will definitely be in touch. :)  Thanks again.

**Comment by tantrev** [comment]
Just thought I might share this article that describes some limitations with the UNITE database for fungal hits: http://geoffreyzahn.com/limitations-of-the-unite-fungal-database/ 

I'll keep my fingers crossed for any future NCBI additions to Taxonomer. :)

**Comment by stevendflygare** [comment]
Excellent point about the limitations of UNITE.  Thanks for sharing!
